name: Build Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'

permissions:
  packages: write

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit
  
  build:
    uses: ./.github/workflows/docker.yml
    needs: check
    with:
      image: ghcr.io/donicrosby/linkpedant
    secrets: inherit
