name: Build Image

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
    tags:
      - 'v*.*.*'

permissions:
  packages: write

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit
  
  build:
    uses: ./.github/workflows/docker.yml
    if: ${{ github.ref == '/refs/heads/master' }}
    needs: check
    with:
      image: ghcr.io/donicrosby/linkpedant
    secrets: inherit
