name: Run Rust Lints

on:
  pull_request:
    branches:
      - 'master'
      - 'dev'
  push:
    branches:
      - 'dev'
      
jobs:
  lint-and-check:
    uses: ./.github/workflows/check.yml
    secrets: inherit
